// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2ITkZPl-Olwn1k7KYlD6k5Wq7M6QiICk',
    appId: '1:857370261728:web:5f758c2ee52a67a23cb885',
    messagingSenderId: '857370261728',
    projectId: 'credcheck-22065',
    authDomain: 'credcheck-22065.firebaseapp.com',
    storageBucket: 'credcheck-22065.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjGjD3FmwWbPFJOquEKKNIgNY9vK8hHJ8',
    appId: '1:857370261728:android:fd89b4ed0ecffeba3cb885',
    messagingSenderId: '857370261728',
    projectId: 'credcheck-22065',
    storageBucket: 'credcheck-22065.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB27kEGb9aksnSj3z0oHaNuHbklnCbMiCM',
    appId: '1:857370261728:ios:1683744f7e061e993cb885',
    messagingSenderId: '857370261728',
    projectId: 'credcheck-22065',
    storageBucket: 'credcheck-22065.appspot.com',
    iosBundleId: 'com.example.credcheck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB27kEGb9aksnSj3z0oHaNuHbklnCbMiCM',
    appId: '1:857370261728:ios:d816693eb0a41db93cb885',
    messagingSenderId: '857370261728',
    projectId: 'credcheck-22065',
    storageBucket: 'credcheck-22065.appspot.com',
    iosBundleId: 'com.example.credcheck.RunnerTests',
  );
}
